# Jean pockets

Are women jean pockets ridiculously small? Let's look at the data!

The file `jean-pocket-measurements.csv` shows pocket measurements for 20 popular brands.
Four pairs of jeans from each brand were measured: men's and women's skinny and straight styles. All jeans were designated a 32-inch waistband. 

The following measurements are included:
- `height_front`: maximum front pocket height (cm)
- `height_back`: maximum back pocket height (cm)
- `width_front`: maximum front pocket width (cm)
- `width_back`: maximum back pocket width (cm)

In [ ]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'jean-pocket-measurements.csv'.

# from google.colab import files
# uploaded = files.upload()

In [3]:
import pandas as pd
df = pd.read_csv('jean-pocket-measurements.csv')
df.head(10)

,brand,style,gender,height_front,width_front,height_back,width_back
0,3fe5003e,skinny,women,14.5,16.5,15.0,13.7
1,3fe5003e,straight,women,14.5,16.0,15.5,13.0
2,790c6eab,skinny,women,13.0,14.5,15.5,13.5
3,790c6eab,straight,women,13.0,14.5,14.5,13.0
4,26aaf627,skinny,women,13.0,14.0,14.0,14.2
5,26aaf627,straight,women,15.5,16.5,14.5,12.5
6,ba56feb3,skinny,women,12.0,14.5,16.5,13.0
7,ba56feb3,straight,women,14.0,15.5,15.0,14.0
8,7398d4c6,skinny,women,13.0,13.5,16.0,14.5
9,7398d4c6,straight,women,15.0,15.5,14.5,13.0

### Project Ideas

- What is the average difference in pocket `height_front` between women's and men's jeans?

- Is there a significant difference in pocket `height_front` between skinny and straight styles within the same gender?

- How do back pocket sizes compare between women's and men's jeans?

- Measure your phone's height. What percentage of women's and men's jeans can comfortably fit your phone in the pockets?

In [9]:
# What is the average difference in pocket height_front between women's and men's jeans?
promedio = df.groupby('gender')['height_front'].mean()
promedio
diferencia = abs(promedio['women'] - promedio['men'])
print(f"La diferencia promedio es de  {diferencia:.2f} unidades entre generos")

La diferencia promedio es de  8.80 unidades entre generos

In [13]:
men = df.query('gender == "men"')
promediostyle = men.groupby('style')['height_front'].mean()
diferenciastylemen = abs(promediostyle['skinny'] - promediostyle['straight'])
print(f"La diferencia promedio es de  {diferenciastylemen:.2f} unidades entre estilos de hombre")

La diferencia promedio es de  0.11 unidades entre estilos de hombre

In [14]:
women = df.query('gender == "women"')
promediostyle = women.groupby('style')['height_front'].mean()
diferenciastylewomen = abs(promediostyle['skinny'] - promediostyle['straight'])
print(f"La diferencia promedio es de  {diferenciastylewomen:.2f} unidades entre estilos de mujer")

La diferencia promedio es de  0.12 unidades entre estilos de mujer

In [16]:
phonesize=15.5
pf = df
pf['fit_front'] = pf['height_front'] >= phonesize
pf['fit_back'] = pf['height_back'] >= phonesize

In [17]:
#- Measure your phone's height. What percentage of women's and men's jeans can comfortably fit your phone in the pockets?
porcentaje = pf.groupby('gender')[['fit_front','fit_back']].mean()
porcentaje

        fit_front  fit_back
gender
men           1.0     0.775
women         0.2     0.400